-- SELECT * FROM tempdb.INFORMATION_SCHEMA.TABLES 
-- WHERE TABLE_NAME LIKE '#LocalTempTable%';

-- SELECT * FROM #LocalTempTable;

SELECT * FROM tempdb.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '##GlobalTempTable%';

SELECT * FROM ##GlobalTempTable;

-- SELECT * FROM tempdb.INFORMATION_SCHEMA.TABLES 
-- WHERE TABLE_NAME LIKE @TableVar;

-- SELECT * FROM @TableVar;